image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: "Docker Login"
        script:
          - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - step:
        name: "Docker build e Push da Imagem"
        caches:
          - docker
        script:
          - docker build -t isadoraxavierr/ruby-2.7.4:v$BITBUCKET_BUILD_NUMBER -t isadoraxavierr/ruby-2.7.4:latest .
          - docker push isadoraxavierr/ruby-2.7.4:v$BITBUCKET_BUILD_NUMBER
          - docker push isadoraxavierr/ruby-2.7.4:latest

    - step:
        name: "Deploy no Azure App Service"
        deployment: production
        script:
          - pipe: atlassian/azure-web-apps-deploy:1.0.2
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_APP_NAME: "maisart-api"
              AZURE_APP_SERVICE_NAME: "maisart-api"
              CONTAINER_IMAGE_NAME: "isadoraxavierr/ruby-2.7.4:v$BITBUCKET_BUILD_NUMBER"
