services:

  db:
    container_name: maisart-db-dev
    image: postgres:12.17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: api_maisart_development
    volumes:
      - db-docker-vol:/var/lib/postgresql/data
    networks:
      - maisart_net
  maisart-api:
    container_name: maisart-back
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - maisart_net
    environment:
      PASSWORD_DB: admin
      USERNAME_DB: postgres
      database: api_maisart_development
      HOST_DB: db
    command: ./entrypoint.sh
  web:
    container_name: maisart-web
    image: isadoraxavierr/maisart-web
    restart: always
    ports: 
      - 8080:8080
    networks:
      - maisart_net
volumes: 
  db-docker-vol:
    name: postgre-db-maisart-vol-dev
networks:
  maisart_net:
    driver: bridge
